# Generated by Django 3.2.19 on 2023-06-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название места')),
                ('description_short', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
                ('description_long', models.TextField(blank=True, null=True, verbose_name='Длинное описание')),
                ('coordinate_lat', models.FloatField(verbose_name='Широта')),
                ('coordinate_lng', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
