# Generated by Django 4.2.2 on 2023-06-12 10:36

from django.db import migrations

def replace_none_with_blank_string(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        if place.description_short is None:
            place.description_short = ''
        if place.description_long is None:
            place.description_long = ''
        place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20230604_0929'),
    ]

    operations = [
        migrations.RunPython(replace_none_with_blank_string),
    ]


